
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package frontend;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RIGHT_PAREN = 20;
  public static final int RIGHT_SQUARE_BRACKET = 22;
  public static final int INT = 37;
  public static final int LEFT_CURLY = 17;
  public static final int MINUS = 31;
  public static final int STATIC = 4;
  public static final int SEMICOLON = 24;
  public static final int AND = 27;
  public static final int BANG = 26;
  public static final int COMMA = 23;
  public static final int CLASS = 2;
  public static final int RIGHT_CURLY = 18;
  public static final int INT_T = 14;
  public static final int PLUS = 30;
  public static final int MAIN = 6;
  public static final int IF = 9;
  public static final int THIS = 33;
  public static final int ID = 38;
  public static final int DOT = 25;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int TRUE = 36;
  public static final int LEFT_SQUARE_BRACKET = 21;
  public static final int NEW = 34;
  public static final int error = 1;
  public static final int BOOLEAN_T = 15;
  public static final int VOID = 5;
  public static final int EQ = 28;
  public static final int TIMES = 32;
  public static final int ELSE = 11;
  public static final int WHILE = 10;
  public static final int SYSOUT = 12;
  public static final int PUBLIC = 3;
  public static final int EXTENDS = 7;
  public static final int LEFT_PAREN = 19;
  public static final int FALSE = 35;
  public static final int LESS_THAN = 29;
  public static final int STRING_T = 16;
  public static final int LENGTH = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "EXTENDS",
  "RETURN",
  "IF",
  "WHILE",
  "ELSE",
  "SYSOUT",
  "LENGTH",
  "INT_T",
  "BOOLEAN_T",
  "STRING_T",
  "LEFT_CURLY",
  "RIGHT_CURLY",
  "LEFT_PAREN",
  "RIGHT_PAREN",
  "LEFT_SQUARE_BRACKET",
  "RIGHT_SQUARE_BRACKET",
  "COMMA",
  "SEMICOLON",
  "DOT",
  "BANG",
  "AND",
  "EQ",
  "LESS_THAN",
  "PLUS",
  "MINUS",
  "TIMES",
  "THIS",
  "NEW",
  "FALSE",
  "TRUE",
  "INT",
  "ID"
  };
}

